#!/bin/zsh
# Change the shebang alongside $SHELL output

# Whenever new dotfiles are used, create a new variable to store each one of them.

tmux='.tmux.conf'
zsh='.zshrc'
bash='.bashrc'
tmux_folder='.tmux'
rc='rc'
shell=$(which $SHELL)
wd=$(pwd)
arg=$1

new_changes(){
	cp ~/$tmux $wd/$tmux
	cp ~/$zsh $wd/$zsh 
	cp ~/$bash $wd/$bash 
	cp ~/.ssh/$rc $wd/$rc
  cp -r ~/$tmux_folder $wd/$tmux_folder 
}

helper(){
	echo " -c \t Copy all the changes made in dotfiles at root directory to this repository\n -s \t Set all dotfiles in root directory\n -h \t Helper."
}

setup(){
	cp $wd/$tmux ~/$tmux
	cp $wd/$zsh ~/$zsh
	cp $wd/$bash ~/$bash
	cp $rc ~/.ssh/$rc
  cp -r $wd/$tmux_folder ~/$tmux_folder 

	if [[ $shell == "/bin/zsh" ]]; then
		source ~/$zsh
	elif [[ $shell == "/bin/sh" ]]; then 
		source ~/$bash
	else
		echo "$shell not found."
	fi
	tmux source ~/$tmux
}

if [ "$#" -eq 0 ]; then
 	echo "Pass the params to file.\nUse --h to know which flags are disponible."
 else
 	if [ $arg = "--h" ]; then
 		helper
 	elif [ $arg = "-c" ]; then
 		new_changes
 	elif [ $arg = "-s" ]; then
 		setup
 	else
 		echo "Invalid argument.\nUse --h to know which flags are disponible."
 	fi
fi
